<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>@yield('title')</title>
    <style>
        @page {
            margin: 0cm 0cm;
        }
        body {
            font-family: 'Helvetica', sans-serif;
            margin-top: 3cm;
            margin-bottom: 2cm;
            margin-left: 2cm;
            margin-right: 2cm;
            font-size: 13px;
            color: #333;
        }
        header {
            position: fixed;
            top: 0cm;
            left: 0cm;
            right: 0cm;
            height: 3cm;
            background-color: #f8f9fa;
            color: #333;
            line-height: 1.5cm;
            padding: 0 2cm;
            border-bottom: 1px solid #ddd;
        }
        footer {
            position: fixed;
            bottom: 0cm;
            left: 0cm;
            right: 0cm;
            height: 2cm;
            background-color: #f8f9fa;
            color: #777;
            text-align: center;
            line-height: 1.5cm;
            font-size: 11px;
            border-top: 1px solid #ddd;
        }
        .logo {
            float: left;
            margin-top: 0.5cm;
            max-height: 1.5cm;
        }
        .company-details {
            float: right;
            text-align: right;
            margin-top: 0.5cm;
            line-height: 1.2;
        }
        .company-name {
            font-weight: bold;
            font-size: 16px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th {
            background-color: #f3f4f6;
            text-align: left;
            padding: 8px;
            font-weight: bold;
            border-bottom: 1px solid #ddd;
        }
        td {
            padding: 8px;
            border-bottom: 1px solid #eee;
        }
        .text-right {
            text-align: right;
        }
        .font-bold {
            font-weight: bold;
        }
        .total-row td {
            border-top: 2px solid #ddd;
            font-weight: bold;
        }
        .notes {
            margin-top: 30px;
            font-size: 11px;
            color: #666;
            background: #fffbe6;
            padding: 10px;
            border: 1px solid #ffe58f;
        }
        .meta-table {
            margin-bottom: 30px;
        }
        .meta-table td {
            border: none;
            padding: 2px;
        }
    </style>
</head>
<body>
    <header>
        <!-- Dynamic Logo Logic would go here. For now, text fallback -->
        <div class="logo">
            <h1 style="margin: 0; font-size: 24px;">{{ $brandName ?? '7 Hertz Studio' }}</h1>
        </div>
        <div class="company-details">
            <div class="company-name">{{ $brandName ?? '7 Hertz Studio' }}</div>
            <div>{{ $companyPhone ?? '+92 300 1234567' }}</div>
            <div>{{ $companyEmail ?? 'billing@7hertzstudio.com' }}</div>
            <div>{{ $companyWebsite ?? 'www.7hertzstudio.com' }}</div>
        </div>
    </header>

    <footer>
        Page <span class="pagenum"></span> | Generated by BizFlow Platform
    </footer>

    <main>
        @yield('content')
    </main>
</body>
</html>
